# Generated by Django 3.2.4 on 2021-06-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinput', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uinput',
            name='Day',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)]),
        ),
        migrations.AlterField(
            model_name='uinput',
            name='Expinc',
            field=models.CharField(choices=[('Expense', 'EXPENSE'), ('Income', 'INCOME')], max_length=70),
        ),
        migrations.AlterField(
            model_name='uinput',
            name='Month',
            field=models.CharField(choices=[('January', 'JANUARY'), ('February', 'FEBRUARY'), ('March', 'MARCH'), ('April', 'APRIL'), ('May', 'MAY'), ('June', 'JUNE'), ('July', 'JULY'), ('August', 'AUGUST'), ('September', 'SEPTEMBER'), ('October', 'OCTOBER'), ('November', 'NOVEMBER'), ('December', 'DECEMBER')], max_length=70),
        ),
        migrations.AlterField(
            model_name='uinput',
            name='Tag',
            field=models.CharField(choices=[('-', '-----Expense Choices-----'), ('House Rent', 'House Rent'), ('Grocery', 'Grocery'), ('Vegitables', 'Vegitables'), ('Fuel expenses', 'Fuel expenses'), ('Car loan', 'Car loan'), ('Housing loan', 'Housing loan'), ('Medical expenses', 'Medical expenses'), ('Electricity bill', 'Electricity bill'), ('Water bill', 'Water bill'), ('SIM card recharge', 'SIM card recharge'), ('Internet', 'Internet'), ('Cooking Gas', 'Cooking Gas'), ('Others', 'Others'), ('-', '-----Income Choices-----'), ('Salary', 'Salary'), ('FD Interest', 'FD Interest'), ('Part Time', 'Part Time'), ('Prize money', 'Prize money'), ('Freelancing', 'Freelancing'), ('House rent income', 'House rent income'), ('Others', 'Others')], max_length=70),
        ),
    ]
