# Generated by Django 3.2.4 on 2021-06-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinput', '0004_alter_uinput_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='exptable',
            fields=[
                ('Pid', models.IntegerField(primary_key=True, serialize=False)),
                ('Ename', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='tagtable',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('tagname', models.CharField(max_length=70)),
                ('Pid', models.IntegerField()),
            ],
        ),
    ]
