# Generated by Django 3.2.4 on 2021-06-29 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userinput', '0008_auto_20210629_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uinput1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='June', max_length=70)),
                ('Date', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=29)),
                ('Expinc', models.CharField(choices=[('Expense', 'EXPENSE'), ('Income', 'INCOME')], max_length=70)),
                ('Tag', models.CharField(choices=[('-', '-----Expense Choices-----'), ('House Rent', 'House Rent'), ('Grocery', 'Grocery'), ('Vegetables', 'Vegetables'), ('Fuel expenses', 'Fuel expenses'), ('Car loan', 'Car loan'), ('Housing loan', 'Housing loan'), ('Medical expenses', 'Medical expenses'), ('Electricity bill', 'Electricity bill'), ('Water bill', 'Water bill'), ('SIM card recharge', 'SIM card recharge'), ('Internet', 'Internet'), ('Cooking Gas', 'Cooking Gas'), ('School fees', 'School fees'), ('Transportation fees', 'Transportation fees'), ('Hostel fee', 'Hostel fee'), ('Bus pass', 'Bus pass'), ('Gym fee', 'Gym fee'), ('College fee', 'College fee'), ('Others', 'Others'), ('-', '-----Income Choices-----'), ('Salary', 'Salary'), ('FD Interest', 'FD Interest'), ('Part Time', 'Part Time'), ('Prize money', 'Prize money'), ('Freelancing', 'Freelancing'), ('House rent income', 'House rent income'), ('Bit coin', 'Bit coin'), ('Dividends income', 'Dividends income'), ('Side business', 'Side business'), ('Others', 'Others')], max_length=70)),
                ('Amount', models.IntegerField()),
                ('Month_int', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
